controller_list:
  - name: fake_arm_controller
    joints:
      - Shoulder_Joint
      - Arm_Joint
      - Forearm_Joint
      - Wrist_1_Joint
      - Wrist_2_Joint
      - Hand_Joint
  - name: fake_gripper_controller
    joints:
      - Finger_1_Proximal_Joint
      - Finger_2_Proximal_Joint